language: node_js

node_js:
  - "12.19.0"

branches:
  only:
    - dev

# cache:
#   directories:
#     - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - npm run build
