language: node_js

node_js:
  - "12.19.0"

branches:
  only:
    - master

# cache:
#   directories:
#     - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - npm run build

deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: NT265KKsgM5GQTrRHfBIlsNIKxn1BTWraTGsKkdtQiJKAm1nJdRFIzmD5euI4QmEhJv40XWGHAks0/RiRVJrBXQZ/c+e0La9fc+Ud76wjHoAw4uxnqtySF3pp6RvKOlw+3WqLLVALD2Lahaw7rEmpYE42Y37mZp4V9vNHLjxC0uosEC8Z3YoH+0XqsI8hcLNJCArLhez1u78mmLspPnVtYN2W8fjAYKzx7bLqEB1JaX8zpO23IAaqZpbDzG6BmJAhYXgpaCBz7pHHqt+aPPX9eln/zNRBCwLRKhxkSaKOWDAxDr1hGSl7lP2X9jKfTejTSjm4prsx5OGUhfXIs7RUQ4mW7S25FjC9DZDdZrNreBwhHBWzM/IKuBu7bN06O30VtWNapSV7vSLQtQJkJEpVsnH3z3A+p0pI0rMuTiZk/zILi3zWHZ+93bIH94n4w+fdGXuUUL0uUf2PGqW3h48kF6hFNaeKVMkhCyQ7qrPJDVSHq4XGPEMFmRTH8VT+QjqBOV5qdgTz1IFspVU2jvQFxuPbOxwXIvrq7ROTZbt3ZTO7QU4vGY9iqW433vYX4L68M9bIJkBfDN5tkShSmdudWCNmCaGwxv+W7vHYIGf0qcLoef9T19Wipq1rrYH5V+Cc6y7F5TgpQDHH3FbGWqvIhq9BUPmpjgr07J0mkRxJ8A=
  api-key:
    secure: NT265KKsgM5GQTrRHfBIlsNIKxn1BTWraTGsKkdtQiJKAm1nJdRFIzmD5euI4QmEhJv40XWGHAks0/RiRVJrBXQZ/c+e0La9fc+Ud76wjHoAw4uxnqtySF3pp6RvKOlw+3WqLLVALD2Lahaw7rEmpYE42Y37mZp4V9vNHLjxC0uosEC8Z3YoH+0XqsI8hcLNJCArLhez1u78mmLspPnVtYN2W8fjAYKzx7bLqEB1JaX8zpO23IAaqZpbDzG6BmJAhYXgpaCBz7pHHqt+aPPX9eln/zNRBCwLRKhxkSaKOWDAxDr1hGSl7lP2X9jKfTejTSjm4prsx5OGUhfXIs7RUQ4mW7S25FjC9DZDdZrNreBwhHBWzM/IKuBu7bN06O30VtWNapSV7vSLQtQJkJEpVsnH3z3A+p0pI0rMuTiZk/zILi3zWHZ+93bIH94n4w+fdGXuUUL0uUf2PGqW3h48kF6hFNaeKVMkhCyQ7qrPJDVSHq4XGPEMFmRTH8VT+QjqBOV5qdgTz1IFspVU2jvQFxuPbOxwXIvrq7ROTZbt3ZTO7QU4vGY9iqW433vYX4L68M9bIJkBfDN5tkShSmdudWCNmCaGwxv+W7vHYIGf0qcLoef9T19Wipq1rrYH5V+Cc6y7F5TgpQDHH3FbGWqvIhq9BUPmpjgr07J0mkRxJ8A=
  app:
    master: smart-idea-frontend
