language: node_js

node_js:
  - "14.17.6"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod
  # - npm run coverall

# after_success:
#   - npm run build

branches:
  only:
    - dev
# before_deploy:
#   - "echo 'before deploying'"
# deploy:
# provider: heroku
# on:
#   branch: main
# api_key:
#   secure:
# app:
#   master: bongo-jobs-dev
# skip_cleanup: true

# notifications:
#   slack:
#     secure:

# after_deploy: echo 'after deployed'
