language: node_js

node_js:
  - "12.19.0"

branches:
  only:
    - main

# cache:
#   directories:
#     - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - npm run build

deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: "ZrMqQzPdfvGWJx/tqltmHRP5wALaGR/aVg92aZSSLC5QfiXD+d4ivZixcpnUMoui2KGjxKjY2UvYvqo/isZtTH1cTDKQiSe5KmM3/DaVDZtl8CoOb6D4GiBuxy1VP+5si/s6vW3c2exfu4mY7f6FXOW6OKShA/5JguwVeCRXsPBCnmfIzKO0jCv9NC9Z3vMduOLwA36gVoIaG2z3IiL8G+9dfAl5lOS6tB88atQ/ZBQ0cmPnSCB2i6W90F3zYG5Avl3NiVfx+Tsce6NMNmtskD6fc0ffYNmj4ynsAZrZmX2UdeIwxNeMzKAW7Lx3KOiE7WMYQr+b50vXKaUj5eRYHZZ6foxx9S/lWwOyYawjiJfpsrmEC2iXUMkovRDzvtNNEzmijCoUy3tS7CSYYsMjE4V1D6yEcXD0gJSKS1Ax/wHPbKPHZI2puq7k3aiKRPUjV+fYvKSovkYUmosDV6aIq1s/BpDwlmtKbVxsM8HbNqhGQxwd6/SlVKzfJZT+oZaQFnlnVxXwbyrQbPlAyTgtwZfOS5JKz/vuCH6x/QvzLF9lhJO2UciTe311uVXuqOxzZ8MUlHvKpowr8fMTjoLbYNsL4zKmkx7S26t1fnrMr6evAfTUNqRMpn/3HwSPSYiKjTXXJBymBonwiXcySVOvqmLnCBosby8RJzHGKDJaqYY="
  app: smart-idea-frontend
