language: node_js
node_js:
  - 12.19.0
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
deploy:
  provider: heroku
  on:
    branch: master
  api_key:
    secure: AIOepu0ieueSdhP57TW2JdomRwOPnncwXv2x/byvSteAquU66KWoWILsva9G88+OiO7xnB9vALVJjkUM6ypAuuEUcNQbJws34GowhkHGbfXglEK42tzrAfJRZk7IBHSTKNAI44p1RxTfMwljBVFuQI1Vpx4vqq1HJ1ymvNtLagBREIRb+jTP+jH2gzSeT/q/n8QzXkb98IHvKky+kgxST68sq5RgPB9YKEhMyhBoXBUj6JO2Xhh4A3SjUWvKA+QYkVjxT72Yh5ewZpWYOdCecTjSeUyHOPPHXpQJzlPN3rA0YNIMRNWFk3kiyWI3vs4/PA7X+hFzuhVlN05MS7VvCF9CaXFnhzeWo4rd8+vmO/r8C/oBCNVnz9/WYmm6RClx+CRGajf1ndjB5hj5+A3jc79HsJQsQA7/CdEisghMsXTdXaEDb3e5pkDoowRXGrm7FZ8M+sHfQqqkhjYDJypEhKMS57YZo9/Bm77NHUdkvoSw31ht6tbwnET/gq4d6kj5pOfbH9ZQtgcWzyOKAK5k7afsoBAoyHwGjji/Gp6cO9wnOsV3wy1gT3q4nXE615NUQy2UcPqqz6cxKE3IJvRuVOHoD9ac3FvNNVLA4pXtFOXF5jyTxME+lfFmAgX5X/Yh2Sj+r3awKU9Di8/tNmmV4ZEYph+2FK5i9uA83N33xcs=
  app:
    master: smart-idea-frontend
