language: node_js

node_js:
  - "12.19.0"

dist: trusty

branches:
  only:
    - dev

cache:
  directories:
    - node_modules

before_script:
  - npm install
  - npm install -g @angular/cli

script:
  - ng build
