language: node_js

node_js:
  - "12.19.0"

branches:
  only:
    - dev

# cache:
#   directories:
#     - node_modules

before_script:
  - npm install -g @angular/cli
  - npm install har-validator@latest --save-dev

script:
  - npm install
  - ng build
